### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dedors** [Ludy87/ipv64#145]
### What version of Integration has the issue?

1.7.3

## System Information

version | core-2024.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Zurich
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.1
Stage | running
Available Repositories | 1469
Downloaded Repositories | 42

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 58.4 GB
disk_used | 44.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), Mosquitto broker (6.4.1), Terminal & SSH (9.15.0), InfluxDB (5.0.1), Studio Code Server (5.17.3), Advanced SSH & Web Terminal (19.0.0), Glances (0.21.1), ESPHome Device Compiler (2024.11.2), Spotify Connect (0.13.0), Let's Encrypt (5.2.5), Nextcloud Backup (0.17.7), Zigbee2MQTT (1.41.0-1), TasmoAdmin (0.31.0), AdGuard Home (5.1.5), etrv-scan (0.03), etrv2mqtt (0.03), Duck DNS (1.18.0), OpenThread Border Router (2.12.1), Vaultwarden (Bitwarden) (0.23.5), Matter Server (6.6.1), Whisper (2.2.0), Piper (1.5.2), Silicon Labs Flasher (0.3.1), Zigbee2MQTT Edge (edge), Music Assistant Server (2.3.3), openWakeWord (1.10.0), ZigStar TI CC2652P/P7 FW Flasher (0.4.1), Frigate (0.14.1), Frigate (Full Access) (0.14.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 29
views | 49
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17 November 2024 at 23:52
-- | --
current_recorder_run | 27 November 2024 at 23:21
estimated_db_size | 1764.72 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Newly setup ipv64 account and new addon installation. After the setup, t he integration shows "Failed setup, will retry: list index out of range". It keeps retrying without success.
I have a free ipv64 account with 3 registered dyndns.
Deleted and readded integration, just to be sure.

### Reproduction steps

1. Add repo & reboot
2. Configure integration
3. View integration
...

### Debug logs

```text
2024-11-27 23:26:28.428 DEBUG (MainThread) [custom_components.ipv64] Configure based on config entry XXXX
2024-11-27 23:26:28.428 DEBUG (MainThread) [custom_components.ipv64.coordinator] Initialize IPv64 data updater
2024-11-27 23:26:28.428 DEBUG (MainThread) [custom_components.ipv64.coordinator] Update the data from IPv64.net
2024-11-27 23:26:28.669 ERROR (MainThread) [custom_components.ipv64.coordinator] Unexpected error fetching ipv64-01JDQT8HEGN5YYWX39EHVTZ5W6 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipv64/coordinator.py", line 142, in _async_update_data
    self.data: dict = await get_domain(session, headers_api, result_account_info, self.data, self.config_entry)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipv64/coordinator.py", line 60, in get_domain
    CONF_IP_ADDRESS: result_get_domain["subdomains"][config_entry.data[CONF_DOMAIN]]["records"][0]["content"],
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-11-27 23:26:28.671 DEBUG (MainThread) [custom_components.ipv64.coordinator] Finished fetching ipv64-XXXX data in 0.243 seconds (success: False)
```

**Comment by dedors** [comment]
I can confirm it is working now. Thank you
